### A Single Neuron
Let assume a single neuron having 3 input in it.

<img src="images/single_neuron.png" style="width:500px;height:228px;">

In [2]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

In [3]:
output = (inputs[0]*weights[0] +
          inputs[1]*weights[1] +
          inputs[2]*weights[2] +
          inputs[3]*weights[3] + bias)

output

4.8

### A Layer of Neuron

In [4]:
inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

In [5]:
outputs = [
    # Neuron 1:
    inputs[0]*weights1[0] +
    inputs[1]*weights1[1] +
    inputs[2]*weights1[2] +
    inputs[3]*weights1[3] + bias1,
    # Neuron 2:
    inputs[0]*weights2[0] +
    inputs[1]*weights2[1] +
    inputs[2]*weights2[2] +
    inputs[3]*weights2[3] + bias2,
    # Neuron 3:
    inputs[0]*weights3[0] +
    inputs[1]*weights3[1] +
    inputs[2]*weights3[2] +
    inputs[3]*weights3[3] + bias3]

outputs

[4.8, 1.21, 2.385]

In [6]:
# More optimized way

inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

In [67]:
# Output of current layer
layer_outputs = []
# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    # Zeroed output of given neuron
    neuron_output = 0
    # For each input and weight to the neuron
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply this input by associated weight
        # and add to the neuron's output variable
        neuron_output += n_input*weight
    # Add bias
    neuron_output += neuron_bias
    # Put neuron's result to the layer's output list
    layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]


In [68]:
# Not the content of the learning. Just clearing personal doubt. 
a = [1,2,3,5]
b = [1,2,3]

for i,j in zip(a,b):
    print(i,j)

1 1
2 2
3 3


### Tensors, Arrays and Vectors

**Array:** n array as an ordered homologous container.

In [69]:
# Array Example

a = [  
    [1,2,3], 
    [4,5] 
]
# This is not homologous. So, it is not an array.

b = [
    [1,2,3],
    [4,5,6]
]
# This is homologous. So, it is an array.


**Matrix**: A matrix is a 2-dimensional array.

In [12]:
# Matrix Example 

list_matrix_array = [[4, 2],
                    [5, 1],
                    [8, 2]]

# The first dimension is what’s inside the most outer brackets, and if we look at the above matrix, we can see 3 lists there: 
# [4,2], [5,1], and [8,2]; thus, the size in this dimension is 3 and each of those lists has to be the same shape to form 
# an array (and matrix in this case). The next dimension’s size is the number of elements inside this more inner pair of 
# brackets, and we see that it’s 2 as all of them contain 2 elements.

In [21]:
list_matrix_array[0][1]

2

**Tensor**: A tensor object is an object that can be represented as an array

In [22]:
# Tensor Example

# We couldn't give an object example but can give the representation example 

tolol = [[[1, 5, 6, 2],
        [3, 2, 1, 3]],
        [[5, 2, 1, 2],
        [6, 4, 8, 4]],
        [[2, 8, 5, 3],
        [1, 1,9,4]]]
# This is a 3D Array

# The first level of this array contains 3 matrices:
#           [[1,5,6,2],
#             [3,2,1,3]]
#      And
#           [[5,2,1,2],
#            [6,4,8,4]]
#      And
#           [[2,8,5,3],
#            [1,1,9,4]]

# That’s what’s inside the most outer brackets and the size of this dimension is then 3. If we look
# at the first matrix, we can see that it contains 2 lists — [1,5,6,2] and [3,2,1,3] so the
# size of this dimension is 2 — while each list of this inner matrix includes 4 elements. These 4 elements make up the 3rd and 
# last dimension of this matrix since there are no more inner brackets. Therefore, the shape of this array is (3, 2, 4) and it’s 
# a 3-dimensional array, since the shape contains 3 dimensions.

**Vector**: A vector is a list in Python or a 1-dimensional array in NumPy. This can be multi-dimensional

### Dot Product and Vector Addition

In [23]:
a = [1, 2, 3]
b = [2, 3, 4]

dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
print(dot_product)  

# Now, what if we called a “inputs” and b “weights?” Suddenly, this dot product looks like a succinct way to perform the 
# operations we need and have already performed in plain Python.

20


### A Single Neuron with NumPy

In [24]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

In [25]:
outputs = np.dot(weights, inputs) + bias
print(outputs)

4.8


### A Layer of Neurons with NumPy

In [29]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

In [27]:
layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


In [28]:
# The np.dot() method treats the matrix as a list of vectors and performs a dot product of each of those vectors with the other 
# vector. In this example, we used that property to pass a matrix, which was a list of neuron weight vectors and a vector of 
# inputs and get a list of dot products — neuron outputs.

### A Batch of Data

To train, neural networks tend to receive data in batches. So far, the example input data have been
only one sample (or observation) of various features called a feature set.

Often, neural networks expect to take in many samples at a time for two reasons. One reason is that it’s faster to train in batches in parallel processing, and the other reason is that batches help with generalization during training. 

In [30]:
# An example of a batch of data could look like:

batch = [[1, 2, 3, 2.5], 
        [2, 5, -1, 2], 
        [-1.5, 2.7, 3.3, -0.8]]

# This list of lists could be made into an array since it is homologous. 
# Note that each “list” in this larger list is a sample representing a feature set. 
# [1, 2, 3, 2.5], [2, 5, -1, 2], and [-1.5, 2.7, 3.3, -0.8] are all samples, 
# and are also referred to as feature set instances or observations.

In [79]:
# In this example, we need to manage both matrices as lists of vectors and perform 
# dot products on all of them in all combinations, resulting in a list of lists of outputs, 
# or a matrix; this operation is called the matrix product.

### Matrix Product

The matrix product is an operation in which we have 2 matrices, and we are performing dot products of all combinations of rows from the first matrix and the columns of the 2nd matrix, resulting in a matrix of those atomic dot products

In [80]:
# To perform a matrix product, the size of the second dimension of the left matrix 
# must match the size of the first dimension of the right matrix.

In [81]:
a = [[1,2,3]]

b = [
    [1],
    [2],
    [3]
]

np.dot(a,b)

array([[14]])

### Transposition for the Matrix Product

Transposition simply modifies a matrix in a way that its rows become columns and columns become rows.

Vector dot product need transpose: <br>
<img src="images/transpose.png" style="width:300px;height:150px;">

In [82]:
a = [1,2,3]

row_expd = np.expand_dims(np.array(a), axis=0)     # Add the dimension(1) at the beginning. New dimension: 1x3
column_expd = np.expand_dims(np.array(a), axis=1)  # Add the dimension(1) at the ending. New dimension: 3x1

print("Row Expand:\n", row_expd)
print("Column Expand:\n", column_expd)

Row Expand:
 [[1 2 3]]
Column Expand:
 [[1]
 [2]
 [3]]


In [83]:
# Transpose
import numpy as np

a = [1, 2, 3]
b = [2, 3, 4]

In [84]:
a = np.array([a])
b = np.array([b]).T

print(np.dot(a, b))

[[20]]


In [1]:
# It’s worth mentioning that NumPy does not have a dedicated method for performing matrix product — 
# the dot product and matrix product are both implemented in a single method: np.dot()